// src/constants/termsOfServiceText.ts

export interface TermsHtmlColors {
  background: string;
  text: string;
  primary: string;
  warningBackground: string;
  warningText: string;
  warningBorder: string;
  error: string;
  divider: string;
}

export const getTermsOfServiceHTML = (colors: TermsHtmlColors): string => `
<!DOCTYPE html>
<html lang="en">
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
   <style>
       body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: ${colors.background}; color: ${colors.text}; padding: 20px; line-height: 1.6; font-size: 16px; }
       h1 { color: ${colors.primary}; font-size: 24px; margin-bottom: 10px; border-bottom: 2px solid ${colors.divider}; padding-bottom: 10px; }
       h2 { color: ${colors.text}; font-size: 19px; margin-top: 30px; margin-bottom: 15px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid ${colors.divider}; padding-bottom: 5px; }
       h3 { color: ${colors.text}; font-size: 17px; margin-top: 20px; margin-bottom: 10px; font-weight: 600; opacity: 0.9; }
       p { margin-bottom: 15px; }
       ul, ol { margin-bottom: 15px; padding-left: 20px; }
       li { margin-bottom: 8px; }
       strong { font-weight: 700; }
      .critical { border: 2px solid ${colors.error}; background-color: rgba(255, 0, 0, 0.05); padding: 15px; border-radius: 8px; margin: 20px 0; font-weight: bold; color: ${colors.text}; }
      .warning { border: 1px solid ${colors.warningBorder}; background-color: ${colors.warningBackground}; color: ${colors.warningText}; padding: 15px; border-radius: 8px; margin: 20px 0; }
      .apple-section { border: 1px solid ${colors.divider}; background-color: rgba(128, 128, 128, 0.05); padding: 15px; border-radius: 8px; margin: 20px 0; }
      .footer { margin-top: 40px; border-top: 1px solid ${colors.divider}; padding-top: 20px; font-size: 14px; opacity: 0.7; }
       a { color: ${colors.primary}; text-decoration: none; }
   </style>
</head>
<body>

   <h1>MACROS VISION AI - TERMS OF SERVICE</h1>
   <p><strong>Last Updated: December 1, 2025</strong></p>

   <h2>1. PREAMBLE AND BINDING AGREEMENT</h2>
   <p>These Terms of Service ("Terms") constitute a legally binding contract between you ("User," "You," or "Your") and Danprav (the "Developer," "We," "Us," or "Our"), a legal entity operating under the laws of the State of Israel.</p>
   <p>These Terms govern your access to and use of the Macros Vision AI mobile application (the "App"), its associated website (macros-vision-ai.xyz), its application programming interfaces (APIs), and any related services (collectively, the "Service").</p>
   <p>By downloading, installing, accessing, registering for, or using the App, particularly by clicking "I Agree" in the TermsGate verification screen, you explicitly acknowledge that you have read, understood, and agree to be bound by these Terms.</p>
   
   <div class="warning">
       <strong>WARNING:</strong> SECTION 15 OF THESE TERMS CONTAINS A BINDING ARBITRATION CLAUSE AND CLASS ACTION WAIVER. IF YOU ARE A RESIDENT OF THE UNITED STATES, THIS SECTION AFFECTS YOUR RIGHTS ABOUT HOW TO RESOLVE DISPUTES WITH US.
   </div>

   <h2>2. NATURE OF THE SERVICE: INFORMATION ONLY</h2>

   <h3>2.1 Not a Medical Device</h3>
   <p>The Service is a data aggregation, visualization, and estimation tool designed strictly for general wellness tracking and recreational purposes.</p>
   <ul>
       <li><strong>No Regulatory Clearance:</strong> The App has NOT been cleared, approved, or certified as a medical device by the US Food and Drug Administration (FDA), the European Medicines Agency (EMA), the Israeli Ministry of Health, or any other regulatory body.</li>
       <li><strong>No Diagnostic Capability:</strong> The App is NOT intended to diagnose, cure, mitigate, treat, or prevent any disease, disorder, or physical condition.</li>
   </ul>

   <h3>2.2 Disclaimer of Medical Advice</h3>
   <p>The content generated by the Service, including but not limited to:</p>
   <ul>
       <li>Macronutrient Estimates (Calories, Protein, Carbs, Fat);</li>
       <li>Nutritional Grades (The A-F "Food Grade" scoring system);</li>
       <li>Metabolic Calculations (Basal Metabolic Rate "BMR" and Total Daily Energy Expenditure "TDEE" estimated in the Questionnaire);</li>
   </ul>
   <p>is for informational purposes only. This data is generated by algorithmic estimation and does not constitute medical advice or clinical nutritional counseling. You acknowledge that individual physiological needs vary, and the algorithms used (e.g., Mifflin-St Jeor) are population-based averages that may not apply to your specific biology.</p>

   <h3>2.3 High-Risk Usage Prohibited</h3>
   <p>You expressly agree NOT to use the Service for high-risk medical management, including but not limited to:</p>
   <ol>
       <li>Calculating insulin dosages for Type 1 or Type 2 Diabetes;</li>
       <li>Managing renal (kidney) diets requiring precise potassium/phosphorus tracking;</li>
       <li>Monitoring nutrition during pregnancy or for infants;</li>
       <li>Treating eating disorders (e.g., Anorexia, Bulimia).</li>
   </ol>
   <p><strong>ALWAYS CONSULT A QUALIFIED HEALTHCARE PROVIDER BEFORE MAKING DECISIONS BASED ON DATA FROM THIS APP.</strong></p>

   <h2>3. ARTIFICIAL INTELLIGENCE AND COMPUTER VISION</h2>

   <h3>3.1 Probabilistic Nature of AI</h3>
   <p>The Service utilizes third-party Generative Artificial Intelligence (AI) and Computer Vision technologies (including services accessed via endpoints such as /ai/macros_image_single). You acknowledge and agree that:</p>
   <ul>
       <li><strong>AI is Probabilistic:</strong> The AI predicts the likely content of an image or text description based on statistical patterns. It is NOT deterministic and acts independently of human oversight.</li>
       <li><strong>Hallucinations:</strong> The AI may confidently generate incorrect information ("hallucinations"). For example, it may identify a fried food as grilled, miscalculate portion sizes, or invent ingredients that are not present.</li>
   </ul>

   <h3>3.2 The "Human-in-the-Loop" Doctrine</h3>
   <p>To mitigate the risks of AI error, the Service is designed with a "Human-in-the-Loop" workflow. You agree that the AI functions solely as a drafting assistant. Upon receiving an AI estimate (e.g., via the "Quick Add" modal), YOU ASSUME FULL RESPONSIBILITY TO:</p>
   <ol>
       <li><strong>Verify Identity:</strong> Confirm that the food identified by the AI matches the actual food on your plate.</li>
       <li><strong>Verify Quantity:</strong> Validate that the estimated weight (grams) and portion sizes are accurate.</li>
       <li><strong>Verify Macros:</strong> Cross-reference the caloric and macronutrient values with trusted sources (e.g., packaging labels) before saving the entry to your log.</li>
   </ol>
   <p>By clicking "Add," "Save," or "Update," you adopt the AI-generated data as your own User Content and release the Developer from any liability regarding its accuracy.</p>

   <div class="critical">
       <h3>3.3 CRITICAL ALLERGEN WARNING</h3>
       <p>THE AI CANNOT RELIABLY DETECT ALLERGENS.</p>
       <p>The Computer Vision algorithms analyze visual surface features. It CANNOT detect:</p>
       <ul>
           <li>Hidden ingredients (e.g., peanut oil in a sauce, dairy in a soup);</li>
           <li>Cross-contamination;</li>
           <li>Chemical composition.</li>
       </ul>
       <p>YOU ARE STRICTLY PROHIBITED FROM RELYING ON THE APP TO IDENTIFY ALLERGENS. We expressly disclaim all liability for severe allergic reactions (anaphylaxis), hospitalization, or death resulting from reliance on the App for food safety.</p>
   </div>

   <h2>4. VIRTUAL ECONOMY: COINS AND REWARDS</h2>

   <h3>4.1 "Coins" as a Limited License</h3>
   <p>The Service includes a virtual currency system ("Coins"). You acknowledge that Coins:</p>
   <ul>
       <li>Are a limited, personal, non-transferable, non-sublicensable, revocable license to use specific features of the App (e.g., AI Analysis);</li>
       <li>DO NOT constitute personal property, cryptocurrency, or real-world currency;</li>
       <li>Have NO monetary value and cannot be redeemed for cash, refunds, or credit;</li>
       <li>Are not a stored value account or a deposit.</li>
   </ul>

   <h3>4.2 Dynamic Pricing (Floating Exchange Rate)</h3>
   <p>The Service relies on third-party API providers whose costs fluctuate. To ensure the sustainability of the Service, <strong>WE RESERVE THE RIGHT TO MODIFY THE COIN COST OF ANY FEATURE AT ANY TIME WITHOUT NOTICE.</strong></p>
   <p>For example, a "Food Scan" that costs 5 Coins today may cost 10 Coins tomorrow. The applicable price is the price displayed in the App interface (e.g., the PriceTag component) at the exact moment you initiate the transaction.</p>

   <h3>4.3 Ad-Based Rewards</h3>
   <p>The Service allows you to earn Coins by watching advertisements ("Rewarded Ads").</p>
   <ul>
       <li><strong>Availability:</strong> We do not guarantee the availability of ads at any given time. Ad inventory is controlled by third-party networks (Google AdMob).</li>
       <li><strong>Verification:</strong> Rewards are subject to server-side verification. We reserve the right to withhold rewards if we detect irregular activity, ad-blocking, or network manipulation.</li>
   </ul>

   <h3>4.4 Expiration and Forfeiture</h3>
   <p>We reserve the right to expire and remove unredeemed Coins from your account if your account remains inactive (i.e., no login event recorded) for a continuous period of twelve (12) months. Furthermore, if your account is terminated for a violation of these Terms (see Section 7), all accumulated Coins are forfeited immediately.</p>

   <h2>5. SUBSCRIPTIONS AND PURCHASES</h2>

   <h3>5.1 In-App Purchases</h3>
   <p>The App may offer subscriptions or one-time purchases (e.g., "Pro Mode," "Coin Packs") via the Apple App Store and Google Play Store.</p>
   <ul>
       <li><strong>Billing:</strong> All billing and transaction processes are handled by the respective Store. We do not store your credit card information.</li>
       <li><strong>Auto-Renewal:</strong> Subscriptions automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period.</li>
   </ul>

   <h3>5.2 "Lifetime" Access</h3>
   <p>If you purchase a "Lifetime" subscription, "Lifetime" refers to the operational lifetime of the Service, not your biological lifetime.</p>
   <ul>
       <li>We reserve the right to discontinue the Service or specific features with reasonable notice.</li>
       <li>If the Developer ceases operations or the Service is shut down, your "Lifetime" access terminates, and no refund will be provided, subject to applicable consumer protection laws.</li>
   </ul>

   <h3>5.3 Refunds</h3>
   <ul>
       <li><strong>Apple iOS:</strong> We cannot process refunds for Apple purchases. You must contact Apple Support directly in accordance with their refund policies.</li>
       <li><strong>Android:</strong> Refunds are at our sole discretion or as mandated by Google Play policies. Generally, all sales of Coins are final and non-refundable once the Coins have been credited to your account.</li>
   </ul>

   <h2>6. USER ACCOUNTS AND DATA</h2>

   <h3>6.1 Registration Requirements</h3>
   <p>To access the Service, you must register an account. You agree to:</p>
   <ul>
       <li>Provide accurate, current, and complete information (Age, Sex, Height, Weight).</li>
       <li>Maintain the security of your password.</li>
       <li>Notify us immediately of any unauthorized use of your account.</li>
   </ul>

   <h3>6.2 Age Limitation</h3>
   <p>You must be at least 18 years old to use the Service. By registering, you represent and warrant that you meet this age requirement. If we discover that a user is under 18, we will immediately delete the account and all associated data to comply with child safety regulations.</p>

   <h3>6.3 Account Deletion</h3>
   <p>You may delete your account at any time via the "Settings > Delete Account" menu.</p>
   <ul>
       <li><strong>Effect:</strong> Account deletion is permanent. Your login credentials, food logs, history, and coin balance will be erased.</li>
       <li><strong>Data Retention:</strong> You acknowledge that anonymized User Content (e.g., food images stripped of metadata) that has already been used to train our AI models cannot be "un-learned" or extracted from the aggregate model weights. You grant us permission to retain such anonymized data in perpetuity.</li>
   </ul>

   <h2>7. PROHIBITED ACTIVITIES (ACCEPTABLE USE POLICY)</h2>
   <p>You agree not to engage in any of the following prohibited activities:</p>
   <ol>
       <li><strong>Botting & Fraud:</strong> Using scripts, emulators, auto-clickers, or automation software to view ads, artificially inflate "Streaks," or accumulate Coins.</li>
       <li><strong>Reverse Engineering:</strong> Attempting to decompile, disassemble, or reverse engineer the App’s source code, binary, or API protocols (v1.macros-vision-ai.xyz).</li>
       <li><strong>API Abuse:</strong> Sending excessive requests to our servers that disrupt the Service or generate excessive costs (e.g., scraping).</li>
       <li><strong>Deep Link Abuse:</strong> Using the "Share Food" feature to disseminate content that is offensive, illegal, pornographic, or infringing on intellectual property.</li>
       <li><strong>Circumvention:</strong> Attempting to bypass the "Terms Gate," age verification, or payment mechanisms.</li>
   </ol>
   <p><strong>Consequences:</strong> Violation of this policy may result in the immediate suspension or termination of your account and the forfeiture of all virtual currency without notice or refund.</p>

   <h2>8. INTELLECTUAL PROPERTY RIGHTS</h2>

   <h3>8.1 Developer Rights</h3>
   <p>The Service, including its source code, algorithms, UI design (@rneui/themed implementations), "Food Icon" assets, and databases, is the proprietary property of the Developer and is protected by copyright, trademark, and trade secret laws.</p>

   <h3>8.2 User Content License</h3>
   <p>By submitting content (e.g., uploading food images, editing nutritional data), you grant the Developer a worldwide, non-exclusive, royalty-free, perpetual, irrevocable, and sublicensable license to use, reproduce, modify, adapt, publish, and display such content for the purpose of operating, improving, and promoting the Service.</p>
   <p><strong>Specific Training Consent:</strong> You specifically authorize the Developer to use your anonymized User Content to train and improve Machine Learning and Computer Vision models.</p>

   <h2>9. DISCLAIMER OF WARRANTIES</h2>
   <p>THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
   <p>WE DO NOT WARRANT THAT: (A) THE AI ESTIMATIONS WILL BE ACCURATE; (B) THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE; OR (C) ANY ERRORS IN THE SERVICE WILL BE CORRECTED. YOU ASSUME ALL RISKS ASSOCIATED WITH THE QUALITY AND PERFORMANCE OF THE APP.</p>

   <h2>10. LIMITATION OF LIABILITY</h2>
   <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL THE DEVELOPER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUE, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:</p>
   <ul>
       <li>(A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE;</li>
       <li>(B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE;</li>
       <li>(C) ANY CONTENT OBTAINED FROM THE SERVICE; OR</li>
       <li>(D) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT.</li>
   </ul>
   <p>IN NO EVENT SHALL THE DEVELOPER'S AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE EXCEED THE GREATER OF FIFTY US DOLLARS ($50.00) OR THE AMOUNT PAID BY YOU TO THE DEVELOPER IN THE LAST SIX MONTHS.</p>

   <h2>11. INDEMNIFICATION</h2>
   <p>You agree to defend, indemnify, and hold harmless the Developer and its affiliates from and against any claims, liabilities, damages, losses, and expenses, including reasonable legal fees, arising out of or in any way connected with your access to or use of the Service, your violation of these Terms, or your violation of any third-party right.</p>

   <h2>12. APPLE APP STORE PROVISIONS</h2>
   <div class="apple-section">
       <p>If you downloaded the App from the Apple App Store, the following terms apply:</p>
       <ul>
           <li><strong>Acknowledgment:</strong> These Terms are between you and the Developer only, not Apple.</li>
           <li><strong>Maintenance:</strong> Apple has no obligation to furnish any maintenance or support services with respect to the App.</li>
           <li><strong>Warranty:</strong> In the event of any failure of the App to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price. Apple has no other warranty obligation whatsoever.</li>
           <li><strong>Third-Party Beneficiary:</strong> Apple and its subsidiaries are third-party beneficiaries of these Terms and may enforce them against you.</li>
       </ul>
   </div>

   <h2>13. PRIVACY AND DATA PROTECTION</h2>
   <p>Your use of the App is subject to our Privacy Policy.</p>
   <ul>
       <li><strong>Ad Tracking:</strong> The App uses the Google Mobile Ads SDK. By using the App, you consent to the processing of your data (such as Mobile Advertising IDs) by Google for the purpose of serving personalized advertisements, subject to the privacy settings you select within the App.</li>
       <li><strong>International Transfer:</strong> You acknowledge that your data (including food images) may be transferred to and processed on servers located outside of your country of residence (e.g., to AI providers for analysis).</li>
   </ul>

   <h2>14. GOVERNING LAW AND JURISDICTION</h2>
   <p>These Terms shall be governed by and construed in accordance with the laws of the State of Israel, without regard to its conflict of law principles. You agree to submit to the exclusive personal jurisdiction of the competent courts located in Tel Aviv-Jaffa for the resolution of any disputes arising out of or relating to these Terms or the Service, subject to the arbitration provisions in Section 15.</p>

   <h2>15. DISPUTE RESOLUTION (BINDING ARBITRATION)</h2>
   <p><strong>PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR RIGHTS.</strong></p>

   <h3>15.1 Binding Arbitration (United States Residents)</h3>
   <p>If you are a resident of the United States, you and the Developer agree that any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be determined by binding arbitration, rather than in court. The arbitration shall be administered by the American Arbitration Association (AAA) in accordance with its Consumer Arbitration Rules. The location of the arbitration shall be mutually agreed upon or conducted remotely.</p>

   <h3>15.2 Class Action Waiver</h3>
   <p>YOU AND THE DEVELOPER AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.</p>

   <h3>15.3 Opt-Out</h3>
   <p>You may opt-out of this agreement to arbitrate by emailing us at contact@danprav.me within 30 days of first accepting these Terms, stating your intent to opt-out.</p>

   <h2>16. CHANGES TO TERMS</h2>
   <p>We reserve the right to modify these Terms at any time. If we make material changes, we will notify you by updating the "Last Updated" date at the top of these Terms and, where appropriate, providing notice within the App. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.</p>

   <h2>17. CONTACT INFORMATION</h2>
   <p>For any questions regarding these Terms or the Service, please contact us:</p>
   <p>Danprav<br/>
   Email: <a href="mailto:contact@danprav.me">contact@danprav.me</a></p>

   <div class="footer">
       © ${new Date().getFullYear()} Macros Vision AI. All rights reserved.
   </div>
</body>
</html>
`;