# .github/workflows/android-preview-build.yml
name: EAS Android Preview Build (Local)

# This workflow runs on pushes to the main/master branch, or can be triggered manually.
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android Preview APK
    runs-on: ubuntu-latest
    # CHANGE 1: Assign the job to the 'Production' environment to access its secrets.
    environment: Production

    steps:
      # Step 1: Check out your repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: 'MacroTracker/package-lock.json'

      # Step 3: Set up the Java Development Kit
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 4: Set up the Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Step 5: Install project dependencies
      - name: Install dependencies
        working-directory: ./MacroTracker
        run: npm ci

      # Step 6: Install the EAS CLI globally
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # CHANGE 2: The 'EAS Login' step has been REMOVED. It's not needed.

      # Step 7: Start the EAS Build process
      - name: Build with EAS
        working-directory: ./MacroTracker
        run: eas build --platform android --profile preview --non-interactive --local
        env:
          # CHANGE 3: Pass the token directly to the command that needs it.
          # The EAS CLI automatically uses this environment variable for authentication.
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_BACKEND_URL_PRODUCTION: ${{ secrets.EXPO_PUBLIC_BACKEND_URL_PRODUCTION }}

      # Step 8: Find the generated APK file
      - name: Find APK
        id: find_apk
        run: |
          # CHANGE 4: Search for the APK in the './MacroTracker' directory, not './MacroTracker/android'.
          # The -maxdepth 1 flag prevents 'find' from searching in subdirectories like node_modules, making it faster.
          APK_PATH=$(find ./MacroTracker -maxdepth 1 -type f -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "APK not found!"
            exit 1
          fi
          echo "Found APK at: $APK_PATH"
          echo "path=$APK_PATH" >> $GITHUB_OUTPUT

      # Step 9: Upload the APK as a build artifact
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macros-vision-ai-preview-apk
          path: ${{ steps.find_apk.outputs.path }}