# .github/workflows/eas-build-development-local.yml
name: EAS Development Build (Local)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Development Client (Local)
    runs-on: macos-latest
    
    # This is the fix. It sets the working directory for all subsequent steps.
    # The directory name matches your repository name.
    defaults:
      run:
        working-directory: ./macros-counter # <--- ADD THIS BLOCK

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # We check out the code into a directory named after the repo.
          path: macros-counter

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Set up Bun for faster dependency installation
        uses: oven-sh/setup-bun@v1

      - name: Install project dependencies
        # This will now run inside the 'macros-counter' directory
        run: bun install

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Log in to Expo using a secret token
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build development client locally for Android
        run: eas build --profile development --platform android --local --non-interactive --output builds/MacrosVisionAI-dev.apk

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macrosvisionai-dev-apk
          # The path is now relative to the working directory
          path: macros-counter/builds/MacrosVisionAI-dev.apk